#!/usr/bin/env python3

import src.interpreter
import sys




def runPrompt():
	while True:
		try:
			command = input(">>  ")
		except:
			print("End of session reached.")
			exit()
		src.interpreter.run(command)
				
def runFile():
	text = ""
	try:
		f = open(sys.argv[1])
	except:
		print("Script not found: " + argv[1])
		exit()
	try:
		script = f.read()
	except:
		print("Reading script failed.")	
		exit()
	src.interpreter.run(script)


if len(sys.argv) == 1:
	print("Usage: command line:")
	runPrompt()
elif len(sys.argv) == 2:
	print("Usage: execute file")
	runFile()
else:
	print("Usage: undefined, too many arguments")
	print(sys.argv)
	exit()

